### ISSUE TITLE
Setting OPENAI_API_KEY throws an error : SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by jossefaz** [di-sukharev/opencommit#65]
I followed the setup steps 
When I get to this step : 
```bash
opencommit config set OPENAI_API_KEY=XXXXX
```
I get this error : 
```bash
.nvm/versions/node/v12.13.0/lib/node_modules/opencommit/out/cli.cjs:15050
    throw new Error(`${n} cannot contain ${h(r2?.[0])}`);
                                                ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```
I tried to generate a new API key from OpenAI but it does the same.

**Comment by jossefaz** [comment]
@MartinPaulEve : Upgrading to lts (v18) indeed solved the issue. 
Thanks
