### ISSUE TITLE
Set OPEN_API_KEY failed

### ISSUE THREAD

**Issue by i19s-leopold** [di-sukharev/opencommit#97]
I have tried to set my Open Api key: 
```
opencommit config set OPEN_API_KEY=sk-**********************************
/.nvm/versions/node/v13.14.0/lib/node_modules/opencommit/out/cli.cjs:15050
    throw new Error(`${n} cannot contain ${h(r2?.[0])}`);
                                                                                 ^

SyntaxError: Unexpected token '.'
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1048:15)
    at Module._compile (internal/modules/cjs/loader.js:1082:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by di-sukharev** [comment]
try updating node to latest stable version

**Comment by i19s-leopold** [comment]
My mistake it was due to the outdated version.
